Change pixels per point on mac to be 2 instead of 1
Umatriz/nomi pull request #26
Opened 2024-05-09 15:29 UTC by OlshaMB

2024-05-09 15:35 UTC, Umatriz commented
Making it a setting sound as a really great idea. I would appriciate if you could do it,

2024-05-09 17:56 UTC, OlshaMB commented
Where should I put this setting?
Putting this in the [`Settings`](https://github.com/Umatriz/nomi/blob/main/crates/nomi-core/src/configs/user.rs) doesn't make sense

2024-05-09 17:59 UTC, OlshaMB commented
Also shouldn't nomi-core be stateless(at least storing only storage paths)?

2024-05-09 18:51 UTC, Umatriz commented
> Where should I put this setting? Putting this in the [`Settings`](https://github.com/Umatriz/nomi/blob/main/crates/nomi-core/src/configs/user.rs) doesn't make sense

Make something like `ClientSettings` and put it in the `client` crate

2024-05-09 18:55 UTC, Umatriz commented
> Also shouldn't nomi-core be stateless(at least storing only storage paths)?

I don't understand what do you mean. You may create an issue because it seems to be out of scope for this PR.

2024-05-11 06:53 UTC, Umatriz requested changes

2024-05-11 06:53 UTC, Umatriz commented on crates/client/src/context.rs
> +
Consider using [`cfg!`](https://doc.rust-lang.org/std/macro.cfg.html) macro

2024-05-11 06:53 UTC, Umatriz commented on crates/client/src/context.rs
> +            pixels_per_point: Some(default_pixels_per_point_value()),
Implement `Default`for `ClientSettings` and use it

2024-05-11 06:53 UTC, Umatriz commented on crates/client/src/context.rs
> +            self.client_settings
Maybe use `self.settings_pixels_per_point` there?

2024-05-11 06:55 UTC, OlshaMB commented on crates/client/src/context.rs
> +
This is not comptime

2024-05-11 06:56 UTC, OlshaMB commented on crates/client/src/context.rs
> +            self.client_settings
This makes UI resizing live and janky

2024-05-11 08:33 UTC, merged